version: "3.1"
services:
#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "8000:80"
#      - "443"
#    volumes:
#      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
#      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
#    links:
#      - front-app
#    env_file: ./.env

  serverapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/application
      - /application/node_modules
    links:
      - mysql
    ports:
      - "9000:9000"
    env_file: ./.env
    environment:
      "NODE_ENV": "development"
    tty: true
    stdin_open: true

  mysql:
    env_file: ./.env
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "admin"
      "MYSQL_ROOT_PASSWORD": "admin"

  phpmyadmin:
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin

  frontapp:
    build:
      context: ./park-app
      dockerfile: Dockerfile
    volumes:
      - ./park-app:/application
      - /application/node_modules
    links:
      - serverapp
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
