version: "3.1"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
      - "443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default
      - ./docker/nginx/nginx.conf:/etc/nginx/sites-available/default
    links:
      - app
    env_file: ./.env

  app:
    image: node:latest
    container_name: my-app
    working_dir: /application
    volumes:
      - ./app:/application
    links:
      - mysql
    ports:
      - "9002:9000"
    entrypoint: /application/start_application.sh
    env_file: ./.env
    environment:
      "NODE_ENV": "development"

  mysql:
    env_file: ./.env
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${MYSQL_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${MYSQL_ROOT_PASSWORD}"

  phpmyadmin:
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin

  park-app:
    container_name: park-app
    build:
      context: ./park-app
      dockerfile: Dockerfile
    image: react
    volumes:
      - ./park-app:/usr/src/app/
    links:
      - app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  

   

        
    